### ISSUE TITLE
iptsd-0.4

### ISSUE THREAD

**Issue by supertomi** [parinzee/linux-surface-overlay#2]
this is the result if I try iptsd:

ninja -v -j7 -l0 -C /var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-0.4-10:41:03
ninja: Entering directory `/var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-0.4-build'
ninja: no work to do.
>>> Source compiled.
>>> Test phase [not enabled]: sys-firmware/iptsd-0.4

>>> Install sys-firmware/iptsd-0.4 into /var/tmp/portage/sys-firmware/iptsd-0.4/image
ninja -v -j7 -l0 -C /var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-0.4-build install DESTDIR=/var/tmp/portage/sys-firmware/iptsd-0.4/image
ninja: Entering directory `/var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-0.4-build'
ninja: error: unknown target 'DESTDIR=/var/tmp/portage/sys-firmware/iptsd-0.4/image'
 * ERROR: sys-firmware/iptsd-0.4::linux-surface failed (install phase):
 *   ninja -v -j7 -l0 -C /var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-0.4-build install DESTDIR=/var/tmp/portage/sys-firmware/iptsd-0.4/image failed
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_install
 *   environment, line 2278:  Called eninja '-C' '/var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-0.4-build' 'install' 'DESTDIR=/var/tmp/portage/sys-firmware/iptsd-0.4/image'
 *   environment, line 1105:  Called die
 * The specific snippet of code:
 *       "$@" || die "${nonfatal_args[@]}" "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=sys-firmware/iptsd-0.4::linux-surface'`,
 * the complete build log and the output of `emerge -pqv '=sys-firmware/iptsd-0.4::linux-surface'`.
 * The complete build log is located at '/var/tmp/portage/sys-firmware/iptsd-0.4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sys-firmware/iptsd-0.4/temp/environment'.
 * Working directory: '/var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-master'
 * S: '/var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-master'

>>> Failed to emerge sys-firmware/iptsd-0.4, Log file:

>>>  '/var/tmp/portage/sys-firmware/iptsd-0.4/temp/build.log'

 * Messages for package sys-firmware/iptsd-0.4:
                                                                           10:41:03
 * ERROR: sys-firmware/iptsd-0.4::linux-surface failed (install phase):
 *   ninja -v -j7 -l0 -C /var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-0.4-build install DESTDIR=/var/tmp/portage/sys-firmware/iptsd-0.4/image failed
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_install
 *   environment, line 2278:  Called eninja '-C' '/var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-0.4-build' 'install' 'DESTDIR=/var/tmp/portage/sys-firmware/iptsd-0.4/image'
 *   environment, line 1105:  Called die
 * The specific snippet of code:
 *       "$@" || die "${nonfatal_args[@]}" "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=sys-firmware/iptsd-0.4::linux-surface'`,
 * the complete build log and the output of `emerge -pqv '=sys-firmware/iptsd-0.4::linux-surface'`.
 * The complete build log is located at '/var/tmp/portage/sys-firmware/iptsd-0.4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sys-firmware/iptsd-0.4/temp/environment'.
 * Working directory: '/var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-master'
 * S: '/var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-master'

**Comment by parinzee** [comment]
Right I've changed the ninja function. Could you please try again, please also resync the repo.

**Comment by supertomi** [comment]
No error, but nothing is installed

ninja -v -j7 -l0 -C /var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-0.4-build
ninja: Entering directory `/var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-0.4-build'
ninja: no work to do.
>>> Source compiled.
>>> Test phase [not enabled]: sys-firmware/iptsd-0.4

>>> Install sys-firmware/iptsd-0.4 into /var/tmp/portage/sys-firmware/iptsd-0.4/image
ninja: Entering directory `/var/tmp/portage/sys-firmware/iptsd-0.4/work/iptsd-0.4-build'
ninja: error: unknown target 'DESTDIR=/var/tmp/portage/sys-firmware/iptsd-0.4/image'
>>> Completed installing sys-firmware/iptsd-0.4 into /var/tmp/portage/s11:06:35are/iptsd-0.4/image

 * Final size of build directory: 920 KiB                              11:06:49
 * Final size of installed tree:    4 KiB                              11:07:01

                                                                       11:07:02
>>> Installing (1 of 1) sys-firmware/iptsd-0.4::linux-surface
 * checking 0 files for package collisions
>>> Merging sys-firmware/iptsd-0.4 to /                                11:07:33
>>> sys-firmware/iptsd-0.4 merged.
>>> Regenerating /etc/ld.so.cache...
                                                                       11:07:43
>>> Recording sys-firmware/iptsd in "world" favorites file...
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * Regenerating GNU info directory index...
 * Processed 118 info files.

 * IMPORTANT: 5 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.



root@welle:~> equery f iptsd
 * Searching for iptsd ...
 * Contents of sys-firmware/iptsd-0.4:
root@welle:~>

**Comment by parinzee** [comment]
Apologies for the quality, this should finally be fixed. Please sync and retry.

**Comment by supertomi** [comment]
Jepp!!! Everytghing is fine now :)
