### ISSUE TITLE
layman support

### ISSUE THREAD

**Issue by supertomi** [parinzee/linux-surface-overlay#3]
root@welle:~> layman -a linux-surface

 * Adding overlay...
 * Exception: Overlay "linux-surface" does not exist.

 * CLI: Errors occurred processing action add
 * Exception: Overlay "linux-surface" does not exist.

root@welle:~>

**Comment by parinzee** [comment]
Did you refresh layman? It should support this repo as I've just added it to the gentoo's overlay list. My layman sees the repository just fine from the official list.

![image](https://user-images.githubusercontent.com/30139280/115987411-3925ca00-a5df-11eb-822d-103f402d502e.png)

**Comment by supertomi** [comment]
Now it's just fine!
